### ISSUE TITLE
[1.16.5] the mod's furnace recipes don't show in JEI (might be the same in 1.17)

### ISSUE THREAD

**Issue by Nathan22211** [HexagonNico/ReworkedMetals#10]

**Comment by HexagonNico** [comment]
Hi. Could you provide a better description of the issue? Recipes are shown correctly in JEI for me. Which version of Reworked Metals are you using? Which version of JEI are you using?

**Comment by jxdarker** [comment]
I think what he want to say is we can find the recipe of raw iron to iron ingot via left/right in jei,but we can't find it via left/right click the furnace.
Actually all of the furnace recipe have displayed their recipe in jei,but all of them can't be find via the furnace.You should access it by ingredients and outputs.

**Comment by HexagonNico** [comment]
If that is the case, I can add this feature in the next update.

**Comment by jxdarker** [comment]
Thanks for quickly replying.
But I don’t know whether this is what he means.
Love this mod so much for alloy forgeʕ•ᴥ•ʔ
I’m support U ٩( ᐛ )و

**Comment by Nathan22211** [comment]
yeah that was the issue, right-clicking the furnaces didn't show them in JEI

**Comment by HexagonNico** [comment]
Solved in version 2.0

Closing the issue
