### ISSUE TITLE
ru.Ru Language Translate

### ISSUE THREAD

**Issue by Remyvi12345** [HexagonNico/ReworkedMetals#11]
#10

[ru.ru.zip](https://github.com/HexagonNico/ReworkedMetals/files/7627623/ru.ru.zip)

or

[ru.ru.json.txt](https://github.com/HexagonNico/ReworkedMetals/files/7627626/ru.ru.json.txt)

Hi, I have translated ReworkedMetals into russian language

**Comment by HexagonNico** [comment]
Hi, thank you so much for contributing!

I have uploaded version 2.0.1 to CurseForge to include your translation.

**Comment by Remyvi12345** [comment]
Please fix my nickname in Config there writed "Remivy12345" my own nickname just "Remyvi", thanks in advance.

**Comment by HexagonNico** [comment]
Thanks for letting me know!
I fixed the problem.
