### ISSUE TITLE
[1.18.1, Feature Suggestion?] Furnace Recipes from other mods don't work by default despite what JEI says

### ISSUE THREAD

**Issue by C1ffisme** [HexagonNico/ReworkedMetals#15]
Currently, no modded recipes can be performed by default in any of the furnaces. This is a problem, as the number of furnace recipes in a regular modpack can easily expand into the hundreds range. To make things more confusing, JEI still reports that these recipes can be performed with the retextured Furnace, but such is not the case.

![Screenshot from 2021-12-24 13-54-09](https://user-images.githubusercontent.com/9893266/147370806-3590073e-390e-430f-8079-60905aeb0e96.png)
![Screenshot from 2021-12-24 13-53-55](https://user-images.githubusercontent.com/9893266/147370807-ad523b51-176d-41dc-a91f-cc84dc4a9e7d.png)

(The recipe shown here is from Builders' Crafts & Additions)

I think that it would be useful to have a config option to default all modded Furnace recipes to the Furnace and all modded Blast Furnace recipes to the Blast Furnace, perhaps with a blacklist so that recipes for mundane things like building blocks or ore dusts don't require hours of writing scripts, but you can still decide that something like Quark Frog Legs should only be cooked in a blast furnace for whatever bizarre reason you might have.

While on the subject of JEI as well, the Smeltery doesn't show its recipes in JEI.

**Comment by HexagonNico** [comment]
The recipe showed in JEI is the vanilla "smelting" recipe, Reworked Metals uses another recipe type called "reworked smelting".

For what concerns modded recipes, the only option now is to add the recipe with Craft Tweaker or Open Loader. Allowing all regular smelting recipe to work by default in the new furnaces would break the progression in the mod, as there is no way to tell in which tier of furnace each recipe should work. Adding all the required options in the configs would then become the same as adding the recipe with a json file.

I'm starting to think I should get rid of the furnace-tier system entirely, keep the vanilla furnace as it is, and add an alloying furnace to make alloys. That might be a better idea.

**Comment by C1ffisme** [comment]
> Allowing all regular smelting recipe to work by default in the new furnaces would break the progression in the mod, as there is no way to tell in which tier of furnace each recipe should work.

That's why I suggested what I suggested: allow furnace recipes to automatically be assigned to the new furnace and blast furnace recipes to be automatically assigned to the blast furnace. The smelter will still be used to smelt the limited number of recipes from this mod. A blacklist would exist in the configs to assist in excluding recipes that shouldn't be included in the automatic transfer of recipes.

Nothing here would invalidate the ability to fully customize recipes as before, but for repetitive recipes like smelting dusts into ingots, new wood types into charcoal, tools into recycled metal nuggets, etc. this would make it far easier to just plug-and-play mods without needing to try and throw together a CraftTweaker script that fixes everything. 

(A little bit of broken balance is fine too with default mod behavior, but from the perspective of the modpack maker it's probably better to have some sensible defaults that need a few changes for balance v.s. needing to add back in 100-200 furnace recipes)

**Comment by LittleLyla** [comment]
I agree honestly - I've no clue how to add smelting recipes since the "data/<name>/recipes/custom_recipes.json" doesn't exist or that path exist in **my** instances, so I've resorted to just adding some mekanism ores to just be smelted right away but shapeless crafting. I like the tier system, but it's hard for someone making a modpack.

(Also realized I can't even smelt normal cobblestone?)

**Comment by HexagonNico** [comment]
Hi. Version 3.0-Pre2 has been uploaded and the furnace-tier system has been drastically changed. The vanilla furnace and blast furnace now work the same as they do in vanilla, which means they are now compatible with recipes from other mods. The alloying furnace and the alloying blast furnace are now used to create alloys.

However, some vanilla recipes, such as iron and gold smelting, have been changed to require you to use the blast furnace.

If you want to restrict some recipes to a specific tier you can still do so with Craft Tweaker or Open Loader, but you are no longer *forced* to do so.
