### ISSUE TITLE
Alloy furnace placement crash

### ISSUE THREAD

**Issue by CodexArchive** [HexagonNico/ReworkedMetals#17]
I'm working on a modpack that uses R.M. and whenever I place down the basic alloy furnace it crashes the world and prevents it from being usable. Here's the crash log from when it first happened; not sure if it's something that can be fixed from your mod's end or if it's to do with one of the other mods, but hopefully you can make more sense of it than I can.

[crash-2022-01-25_10.14.58-server.txt](https://github.com/HexagonNico/ReworkedMetals/files/7934972/crash-2022-01-25_10.14.58-server.txt)

**Comment by HexagonNico** [comment]
Hi. It is not happening on my side, it might be due to the version of Forge, since Forge for 1.18 is still in beta. I will make some tests with other versions of Forge and see if I can fix it.

**Comment by HexagonNico** [comment]
I have uploaded a new version on CurseForge which should have fixed the issue. It should now work with any version of Forge.
