### ISSUE TITLE
Alloy Smelter only version and Crafttweaker compatibility

### ISSUE THREAD

**Issue by NixityNull** [HexagonNico/ReworkedMetals#18]
I was hoping maybe you could make a version with only the alloy smelter for compatibility with other mods, and maybe crafttweaker compatibility/integration (if there isn't already) for modpack makers

**Comment by HexagonNico** [comment]
Adding compatibility with other mods would mean adding a recipe for every mod in existence, which is surely not possible.

Craft Tweaker already lets you customise any recipe, there is no need to make changes for compatibility.

Modpack makers can already change recipes and add their own ones.

**Comment by NixityNull** [comment]
by compatibility with other mods, I don't mean that you code in the compatibility, I just meant add a version that only adds the smelter block with no ore generation or recipes so people can use crafttweaker to add their own recipes without having to disable the generation or recipes that the mod already comes with.

**Comment by HexagonNico** [comment]
You can disable the ore generation in the config file.

Another version of the mod that is the same but without crafting recipes would be redundant since recipes can be disabled with CraftTweaker or OpenLoader.
