### ISSUE TITLE
[1.17] Blast furnace can't smelt other ores. Alloying is not working.

### ISSUE THREAD

**Issue by ffuentesm** [HexagonNico/ReworkedMetals#3]
Mod ver: reworkedmetals-1.0.1-1.17.1.jar, SimpleOres2-1.17.1-3.0.1.4.jar, SmallReactors[1.17]-1.9.jar

This mod is great, but for some reason, I can't smelt ores that aren't from this mod.

![image](https://user-images.githubusercontent.com/44974827/141654633-e1b6be71-18d9-49e1-96cc-4ddd641ccb84.png)

![image](https://user-images.githubusercontent.com/44974827/141654642-502940a2-877f-4305-b979-453528998711.png)

![image](https://user-images.githubusercontent.com/44974827/141654652-0aa2a857-b01f-403c-a36b-ac50379c9baa.png)

Also, allowing is not working. 

![image](https://user-images.githubusercontent.com/44974827/141654697-b0d3fce7-1f12-49ce-b94b-6ba00fd7b33b.png)

**Comment by HexagonNico** [comment]
Hi. The Reworked Furnaces use a different type of smelting recipes, I am looking for a way to make it compatible with other mods. For the time being, if you are developing a modpack you can add the recipe yourself. I have a guide on how to do that here: https://github.com/HexagonNico/ReworkedMetals/wiki/Data-packs

For what concern the smelting of alloys, making steel requires charcoal, not regular coal.

**Comment by ffuentesm** [comment]
could you allow that the recipe book shows up in the UI?
it helps to see which recipes are allowed in those new furnaces.

**Comment by HexagonNico** [comment]
Compatibility with other mods has been improved.
Now you are able to smelt ores from other mods if the result item is in ReworkedMetals.

Modpack authors however still need to add recipes for ingots from other mods, since there is no way to predict the output of the recipe.
