### ISSUE TITLE
Datapack is invalid

### ISSUE THREAD

**Issue by ChiefLogan3010** [HexagonNico/ReworkedMetals#7]
In the last couple updates, upon trying to join a world I've been hit with a notification that my datapacks are invalid. I've checked by disabling only this mod and the issue has gone away, so it's definitely something to do with reworked metals

**Comment by HexagonNico** [comment]
Which Minecraft version are you using? 1.16.5 or 1.17.1?

**Comment by ChiefLogan3010** [comment]
Apologies, I didn’t even know there was a 1.17 version otherwise I would’ve specified, I’m using 1.16.5

**Comment by HexagonNico** [comment]
Found the problem. It was due to copper blocks being referenced as `minecraft:copper_block` and `minecraft:raw_copper_block` as in 1.17 instead of `reworkedmetals:copper_block` and `reworkedmetals:raw_copper_block`.

Fixed in version 1.1.2

**Comment by Morabert** [comment]
I was getting the same problem. 
In addition to that, in the prior version ReworkedMetals made a lot of modded & vanilla cooking recipes uncookable in vanilla & modded furnaces/forges/ovens.
MC: 1.16.5
JDK: 16.0.2
Forge 36.2.5
